---
sort: 100

---
skill: "Quick local setup"
level: 3
text: |
  Running React in Visual Studio
requires:
  - "React basics // Linking, ReactDOM.render"
resources:
  - url: https://scrimba.com/learn/learnreact/local-setup-the-quick-way-co38a4834950b81f65b4187b7
    desc: "Local setup (the quick way)"
    type: video
    lang: en
    status: ok

---
skill: "Proper local setup"
level: 4
text: |
  Running React with Vite
requires:
  - "Composability // Components in separate files"
  - "// JavaScript // Node.js // npm install"
resources:
  - url: https://scrimba.com/learn/learnreact/run-react-locally-with-vite-co5c14c369399240413ef9491
    desc: "Run React locally with Vite"
    type: video
    lang: en
    status: check

---
skill: "React & Netlify"
level: 4
text: |
  Deploying React project with Netlify
requires:
  - "React basics // import React & ReactDOM"
  - "// JavaScript // Node.js // npm install"
  - "// Other // Deployment // Netlify"
resources:
  - url: https://scrimba.com/learn/learnreact/drag-and-drop-deploy-with-netlify-co0cc43c19137835bc361427d
    desc: "Drag and Drop Deploy with Netlify"
    text: |
      Simple way when including React using linking
    type: video
    lang: en
    status: ok
  - url: https://scrimba.com/learn/learnreact/deploy-your-react-app-with-netlify-cz2NaGce
    desc: "Deploy Your React App with Netlify"
    text: |
      More complex way when including React correctly through import React
    type: video
    lang: en
    status: check
